// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example://///////////////////////////////
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFireb//aseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android://
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZFeHXXfsZwek7bKAtmZ630aPOfw790o',
    appId: '1:623862851986:web:f3bbe29cfc34770910794b',
    messagingSenderId: '623862851986',
    projectId: 'mf-sip-7f078',
    authDomain: 'mf-sip-7f078.firebaseapp.com',
    storageBucket: 'mf-sip-7f078.firebasestorage.app',
    measurementId: 'G-QEDTZ7Q8W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJ9uoW_vXxs_PMeBX-2J_420INZWGOdE',
    appId: '1:623862851986:android:d21c3e4403fca39310794b',
    messagingSenderId: '623862851986',
    projectId: 'mf-sip-7f078',
    storageBucket: 'mf-sip-7f078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4XHug4BStaH9N558iwbvsqUnbZYNKa0',
    appId: '1:623862851986:ios:054e8343364d084310794b',
    messagingSenderId: '623862851986',
    projectId: 'mf-sip-7f078',
    storageBucket: 'mf-sip-7f078.firebasestorage.app',
    iosBundleId: 'com.example.mySip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4XHug4BStaH9N558iwbvsqUnbZYNKa0',
    appId: '1:623862851986:ios:054e8343364d084310794b',
    messagingSenderId: '623862851986',
    projectId: 'mf-sip-7f078',
    storageBucket: 'mf-sip-7f078.firebasestorage.app',
    iosBundleId: 'com.example.mySip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeZFeHXXfsZwek7bKAtmZ630aPOfw790o',
    appId: '1:623862851986:web:f3cbce7c5c707bf610794b',
    messagingSenderId: '623862851986',
    projectId: 'mf-sip-7f078',
    authDomain: 'mf-sip-7f078.firebaseapp.com',
    storageBucket: 'mf-sip-7f078.firebasestorage.app',
    measurementId: 'G-3P3RCF4WC7',
  );

}