// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example://///////////////////////////////
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFireb//aseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android://
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjGpFFBFqRnxI1QToxAin0OHXPbigtnEo',
    appId: '1:718782049570:web:f232211ca4b778f383c97b',
    messagingSenderId: '718782049570',
    projectId: 'mfsip-3aa54',
    authDomain: 'mfsip-3aa54.firebaseapp.com',
    storageBucket: 'mfsip-3aa54.firebasestorage.app',
    measurementId: 'G-ZW4H57GNKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvPw7sdK6XQCdaIT7_RqLjtvTLTuFzJg',
    appId: '1:718782049570:android:a87d24f3e1eb373483c97b',
    messagingSenderId: '718782049570',
    projectId: 'mfsip-3aa54',
    storageBucket: 'mfsip-3aa54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3lBHxNzFkZAu-sk-0Zkt-zeLkjGknydg',
    appId: '1:718782049570:ios:70de3f996d7fdc5583c97b',
    messagingSenderId: '718782049570',
    projectId: 'mfsip-3aa54',
    storageBucket: 'mfsip-3aa54.firebasestorage.app',
    androidClientId: '718782049570-h7ioskptkhlcn8prpdq3i1a60o8f4stf.apps.googleusercontent.com',
    iosClientId: '718782049570-67su7tcjak5odsi9tsmbse501p0dgaq1.apps.googleusercontent.com',
    iosBundleId: 'com.kirtihinger.mfsip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3lBHxNzFkZAu-sk-0Zkt-zeLkjGknydg',
    appId: '1:718782049570:ios:ee75a1ed5d85c54783c97b',
    messagingSenderId: '718782049570',
    projectId: 'mfsip-3aa54',
    storageBucket: 'mfsip-3aa54.firebasestorage.app',
    androidClientId: '718782049570-h7ioskptkhlcn8prpdq3i1a60o8f4stf.apps.googleusercontent.com',
    iosClientId: '718782049570-1v1dj9cscjmbhhjseaighr6pt654vt7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mySip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjGpFFBFqRnxI1QToxAin0OHXPbigtnEo',
    appId: '1:718782049570:web:21d74a54b75f7f2983c97b',
    messagingSenderId: '718782049570',
    projectId: 'mfsip-3aa54',
    authDomain: 'mfsip-3aa54.firebaseapp.com',
    storageBucket: 'mfsip-3aa54.firebasestorage.app',
    measurementId: 'G-P86TNS2LRL',
  );

}